#!/bin/sh
set -o errexit -o nounset

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

(
    cd "$SCRIPT_DIR/.."

    echo "Running shfmt..."
    shfmt -s -i=4 -ci -ln=posix -w .
    echo "Done running shfmt."

    swiftlint autocorrect --format .
    swiftformat .
)
