#!/bin/sh
set -o errexit -o nounset

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

(
    cd "$SCRIPT_DIR/.."

    echo "Running shellcheck..."
    shfmt -f . | while read -r fname; do
        shellcheck "$fname" -x -P SCRIPTDIR
    done
    echo "Done running shellcheck."

    echo "Running shfmt..."
    shfmt -s -i=4 -ci -ln=posix -d .
    echo "Done running shfmt."

    swiftlint lint --strict .
    swiftformat --lint .
)
