#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_PATH

main() {
    local scripts
    scripts="$(find "$SCRIPT_PATH"/../{ci,lib,setup} -type f -print0 |
        xargs -0 -n 1 | xargs file | grep '\(bash\|sh\|shell\) script' |
        cut -d: -f1)"

    echo "$scripts" | while read -r fname; do
        shellcheck "$fname"
    done
}

main
